% GCampImaging.m
% 
% created by Srinivas Gorur-Shandilya at 5:55 , 03 December 2015. Contact me at http://srinivas.gs/contact/
% 
% This work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License. 
% To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/4.0/.


% add homebrew path
path1 = getenv('PATH');
if isempty(strfind(path1,':/usr/local/bin'))
    path1 = [path1 ':/usr/local/bin'];
end
setenv('PATH', path1);

% this code determines if this function is being called
calling_func = dbstack;
being_published = 0;
if ~isempty(calling_func)
	if find(strcmp('publish',{calling_func.name}))
		being_published = 1;
		unix(['tag -a publish-failed ',which(mfilename)]);
		unix(['tag -r published ',which(mfilename)]);
	end
end
tic

%% Odour-induced intracellular Calcium in ORNs
% In this document, we document our efforts to determine if intracellular Calcium levels increase on odour. We measure, simultaneously, 
% 
% # the odour stimulus
% # intracellular Calcium signals
% # ORN spiking
% # spiking activity
%
% so this is quite a challenging experiment. 

%% Example Visuals
% In the following figure, we show some example pictures of the antenna in the fluorescence channel. The image is generated by projecting the standard deviation across time for each pixel, and clearly shows the sensilla, and some that respond to the odour. 
%
% <</Users/sigbhu/code/da/images/calcium-imaging.png>>
%

%% Quantitative Analysis of Fluorescence Changes
% In this section we analyse the time course of fluorescence changes as we present a pulse of odour to the antenna. First, we look at one example neuron:

load('/local-data/calcium/merged/2015_12_02_22a_GCamp6_F1_ab3_1.mat')

figure('outerposition',[0 0 600 500],'PaperUnits','points','PaperSize',[1000 500]); hold on
clear l
l1 = plot(data(11).GCamp_time',data(11).GCamp','b'); l1 = l1(end);
l2 = plot(data(1).GCamp_time',data(1).GCamp_control','k'); l2 = l2(end);
l3 = plot(data(1).GCamp_time',data(1).GCamp','r'); l3 = l3(end);
legend([l1 l2 l3],{'Blank Pulse','Odour, control ROI','Odour, Sensilla'})
set(gca,'XLim',[1 19],'YLim',[.9 2])
xlabel('Time (s)')
ylabel('Fluorescence fold change')

prettyFig()

if being_published
	snapnow
	delete(gcf)
end


%% Version Info
% The file that generated this document is called:
disp(mfilename)

%%
% and its md5 hash is:
Opt.Input = 'file';
disp(dataHash(strcat(mfilename,'.m'),Opt))

%%
% This file should be in this commit:
[status,m]=unix('git rev-parse HEAD');
if ~status
	disp(m)
end

t = toc;

%% 
% This document was built in: 
disp(strcat(oval(t,3),' seconds.'))

% tag the file as being published 

if being_published
	unix(['tag -a published ',which(mfilename)]);
	unix(['tag -r publish-failed ',which(mfilename)]);
end
