% 
% 
% created by Srinivas Gorur-Shandilya at 2:01 , 18 February 2016. Contact me at http://srinivas.gs/contact/
% 
% This work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License. 
% To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/4.0/.

pHeader;

%% Inst. Gain Analysis of Synthetic Data
% In this document we generate synethetic data using a LN model and rigorously test our inst. gain analysis methods on the various stimuli that we have. 

%% LN Model
% This is what the LN model that we will use to generate our synthetic data looks like. Note that the filter is slightly differentiating, and that the nonlinearity is saturating, meaning that the local slope gets smaller with larger stimuli. The nonlinearity is plotted for the region of filter outputs that are relevant for this stimulus. 

load('/code/da/data/gaussian_stimulus.mat','gaussian_stimulus')

clear p
p.   tau1 = 25;
p.   tau2 = 60;
p.      A = 0.4000;
p.      n = 2;
p. offset = 0.2769;
p. Hill_A = 100;
p.Hill_Kd = 0.3;
p. Hill_n = 4;

figure('outerposition',[0 0 1000 500],'PaperUnits','points','PaperSize',[1000 500]); hold on
subplot(1,2,1), hold on
[resp,K,shat] = pLNModel(gaussian_stimulus,p);
plot(1e-3*(1:length(K)),K,'k')
xlabel('Filter lag (s)')
ylabel('Filter  (norm)')

subplot(1,2,2), hold on
plot(shat(1:10:end),resp(1:10:end),'k.')
xlabel('Filter Output')
ylabel('LN model output (Hz)')

prettyFig('FixLogX=1;','fs=16;')

if being_published
	snapnow
	delete(gcf)
end

%% Gaussian Stimulus
% First, perform the analysis on Gaussian odor signals. The following figure shows the (real) odour signal and the synthetic ORN response generated by the LN model. 

figure('outerposition',[0 0 1000 800],'PaperUnits','points','PaperSize',[1000 800]); hold on
subplot(2,1,1), hold on
time = 1e-3*(1:length(gaussian_stimulus));
plot(time(1:10:end),gaussian_stimulus(1:10:end),'k')
xlabel('Time (s)')
ylabel('Stimulus (V)')

subplot(2,1,2), hold on
plot(time(1:10:end),resp(1:10:end),'k')
xlabel('Time (s)')
ylabel('ORN Response (Hz)')

prettyFig('FixLogX=1;','fs=16;')

if being_published
	snapnow
	delete(gcf)
end

%%
% Now we back out filters. Since the stimulus is somewhat Gaussian, we expect to back out a filter very close to the original.  

uts = false*(1:length(gaussian_stimulus));
uts(1e4:5e4) = true;
od = ORNData;
od.stimulus = gaussian_stimulus;
od.use_this_segment = uts;
od.firing_rate = resp;
od = backOutFilters(od);

figure('outerposition',[0 0 500 500],'PaperUnits','points','PaperSize',[1000 500]); hold on
plot(1:length(K),K/max(K),'k')
plot((1:length(od.K_firing))-100,od.K_firing/max(od.K_firing),'r')
legend({'Actual Filter','Reconstructed Filter'})
prettyFig('FixLogX=1;','fs=16;')

if being_published
	snapnow
	delete(gcf)
end

%% 
% OK, the filter looks good. Let's look at the full LN model that we can back out of the synthetic data, and also see if we can also back out the nonlinearity. 

plot(od,'LN.firing_rate','data_bin_type','dots')
prettyFig('FixLogX=1;','fs=16;')

if being_published
	snapnow
	delete(gcf)
end

%%
% Now, we begin to test the validity of our methods. We will perform the inst. gain analysis against the linear projection. In the following figure, we plot the distribution of the inst. gain (computed on 50ms bins), and an example plot showing how the inst. gain varies with the mean stimulus in the preceding 200ms. Finally, we summarise plots like this by computing the Spearman correlation as a function of the history length. 

od = computeInstGain(od);
figure('outerposition',[0 0 1500 500],'PaperUnits','points','PaperSize',[1500 500]); hold on
ax(1) = subplot(1,3,1); hold on
ax(2) = subplot(1,3,2); hold on
ax(3) = subplot(1,3,3); hold on

plot(od,ax(1),'pdf.inst_gain_firing');
plot(od,ax(2:3),'instGainAnalysis.firing_rate.mu','data_bin_type','dots','history_length',200);
title(ax(2),'200ms window')
prettyFig('FixLogX=1;','fs=16;')

if being_published
	snapnow
	delete(gcf)
end

%%
% This is weird.  The Spearman correlation gets further away from zero as we move to shorter history lengths. What's going on? Perhaps this is because of the static nonlinearity? Let's repeat the analysis, but compute the inst. gain against the full LN model prediction instead of the simply the linear projection of the stimulus. 

od = computeInstGain(od,true);
figure('outerposition',[0 0 1000 500],'PaperUnits','points','PaperSize',[1000 500]); hold on
clear ax
ax(1) = subplot(1,2,1); hold on
title(ax(1),'200ms')
ax(2) = subplot(1,2,2); hold on

plot(od,ax,'instGainAnalysis.firing_rate.mu','data_bin_type','dots');
ylabel(ax(1),'Inst. Gain (norm)')
prettyFig('FixLogX=1;','fs=16;')

if being_published
	snapnow
	delete(gcf)
end

%%
% The curve is now flat! So we have shown that what we saw previously could be accounted for by a static nonlinearity. This means that in the first analysis (comparing to the linear projection), any timescale we saw there was meaningless. 

%% DA Model synthetic data
% In this section, we use a DA model to generate synthetic data. This model does have a dynamical gain control mechanism by construction. The following figure shows the response generated by the DA model, and the LN model backed out of this synthetic dataset.

clear p
p.   s0 = 7.8242e-04;
p.  n_z = 2;
p.tau_z = 151.1249;
p.  n_y = 2;
p.tau_y = 26.7002;
p.    C = 0.5457;
p.    A = 163.2252;
p.    B = 4.4703;
[resp,y,z,Ky,Kz] = DAModelv2(gaussian_stimulus,p);

clear od
od = ORNData;
uts = false*(1:length(gaussian_stimulus));
uts(1e4:5e4) = true;
od.stimulus = gaussian_stimulus;
od.use_this_segment = uts;
od.firing_rate = resp;
od = backOutFilters(od);

figure('outerposition',[0 0 1000 800],'PaperUnits','points','PaperSize',[1000 800]); hold on
subplot(2,1,1), hold on
plot(time,resp,'k')
title('DA Model output')
xlabel('Time (s)')
ylabel('Firing Rate (Hz)')

clear ax
ax(1) = subplot(2,3,5); hold on
ax(2) = subplot(2,3,6); hold on

plot(od,ax,'LN.firing_rate','data_bin_type','dots')

% also plot the DA model filters
subplot(2,3,4), hold on
plot(1e-3*(1:length(Ky)),Ky)
hold on
plot(1e-3*(1:length(Kz)),Kz)
xlabel('Filter Lag (s)')
title('DA Model filters')
set(gca,'XLim',[0 1])

prettyFig('FixLogX=1;','fs=16;')

if being_published
	snapnow
	delete(gcf)
end

%% 
% We now do a inst. gain analysis using the projected stimulus as before. 

od = computeInstGain(od);
figure('outerposition',[0 0 1500 500],'PaperUnits','points','PaperSize',[1500 500]); hold on
ax(1) = subplot(1,3,1); hold on
ax(2) = subplot(1,3,2); hold on
ax(3) = subplot(1,3,3); hold on

plot(od,ax(1),'pdf.inst_gain_firing');
plot(od,ax(2:3),'instGainAnalysis.firing_rate.mu','data_bin_type','dots','history_length',200);
title(ax(2),'200ms window')
prettyFig('FixLogX=1;','fs=16;')

if being_published
	snapnow
	delete(gcf)
end


%%
% Now we repeat this analysis, but compute the inst. gain vs. the full LN model prediction.

od = computeInstGain(od,true);
figure('outerposition',[0 0 1000 500],'PaperUnits','points','PaperSize',[1000 500]); hold on
clear ax
ax(1) = subplot(1,2,1); hold on
title(ax(1),'200ms')
ax(2) = subplot(1,2,2); hold on

plot(od,ax,'instGainAnalysis.firing_rate.mu','data_bin_type','dots');
ylabel(ax(1),'Inst. Gain (norm)')
prettyFig('FixLogX=1;','fs=16;')

if being_published
	snapnow
	delete(gcf)
end


%%
% The minimum of the Spearman correlation is 500ms, and this compares to the actual timescale of fast gain control of 300ms. 



%% Version Info
pFooter;