% imgSeq2mat.m
% converts an image sequence generated by micro manager into a nice matrix we can work with
% 
% created by Srinivas Gorur-Shandilya at 5:12 , 01 December 2015. Contact me at http://srinivas.gs/contact/
% 
% This work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License. 
% To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/4.0/.


function [images] = imgSeq2mat(path_name)

assert(exist(path_name,'file')==7,'Input argument should be a valid path')
if ~strcmp(path_name(end),oss)
	path_name = [path_name oss];
end

% make output variables
images = (zeros(0,0,0));
c = 1;

allfiles = dir(path_name);

for i = 1:length(allfiles)
	if any(strfind(allfiles(i).name,'tif'))
		temp  = (imread([path_name allfiles(i).name]));
		% temp = uint8(temp/2^(bit_depth-8));
		images(:,:,c) = temp;
		c = c + 1;
	elseif strcmp(allfiles(i).name,'metadata.txt')
		txt = fileread([path_name allfiles(i).name]);
		[andor_elapsed_time,elapsed_time,absolute_time] = metadata2timestamps(txt);
	end
end

% save all of this in a unique file name based on the hash of the metadata
hash = dataHash(txt);
save([path_name 'video_' hash '.mat'],'images','andor_elapsed_time','elapsed_time','absolute_time','-v7.3')

