% ORNDATA/rawData2ORNData.m
% method for the ORNData class which reads files generated by kontroller and loads them into the ORN data class
% 
% created by Srinivas Gorur-Shandilya at 11:23 , 10 February 2016. Contact me at http://srinivas.gs/contact/
% 
% This work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License. 
% To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/4.0/.

function [od] = rawData2ORNData(path_name)

allfiles = dir([path_name oss '*.mat']);

od = ORNData;

for i = 1:length(allfiles)
	temp = [path_name oss allfiles(i).name];
	disp(temp)
	load(temp)
	keyboard
end